Repository openshift/cluster-samples-operator, pull requests merged in 2018-12, with the labels that each got.

#60 update readme with details on config fields, behavior, troubleshooting
  README.md
Labels: approved, lgtm, size/L

#62 add verbose logging config option to operator binary
  cmd/cluster-samples-operator/main.go
Labels: approved, lgtm, size/S

#63 remove configmap and move its contents into SamplesResource.Status
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/L

#65 Modify the secret name and some tiny typos
  README.md
Labels: approved, lgtm, size/M

#64 add git based version information a la openshift/origin
  Dockerfile
  Dockerfile.rhel7
  Makefile
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/operatorstatus/operatorstatus.go
Labels: approved, lgtm, size/S

#66 get centos to rhel transition working via managed to removed back to …
  README.md
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/L
