Repository openshift/cluster-samples-operator, pull requests merged in 2018-10, with the labels that each got.

#22 proper toggling of error messages with ConfigurationValid condition
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/S

#23 fix condition type typo
  pkg/apis/samplesoperator/v1alpha1/types.go
Labels: approved, lgtm, size/XS

#26 bump recent openshift/library xpaas content
  tmp/build/assets/operator/ocp-x86_64/datavirt/imagestreams/jboss-datavirt64-driver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/datavirt/imagestreams/jboss-datavirt64-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/datavirt/templates/datavirt64-basic-s2i.json
  tmp/build/assets/operator/ocp-x86_64/datavirt/templates/datavirt64-extensions-support-s2i.json
  tmp/build/assets/operator/ocp-x86_64/datavirt/templates/datavirt64-ldap-s2i.json
  tmp/build/assets/operator/ocp-x86_64/datavirt/templates/datavirt64-secure-s2i.json
  tmp/build/assets/operator/ocp-x86_64/sso/imagestreams/redhat-sso70-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/sso/imagestreams/redhat-sso71-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/sso/imagestreams/redhat-sso72-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso72-https.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso72-mysql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso72-mysql.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso72-postgresql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso72-postgresql.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso72-x509-https.json
Labels: approved, lgtm, size/L

#27 check for credential before process rhel install with default registry
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/M

#28 protect against hotloop for rhel lack of cred error; add some mutex u…
  pkg/stub/handler.go
Labels: approved, lgtm, size/M

#29 pick up openshift/library updates
  tmp/build/assets/operator/ocp-x86_64/3scale/imagestreams/apicast-gateway.json
  tmp/build/assets/operator/ocp-x86_64/3scale/templates/3scale-gateway.json
  tmp/build/assets/operator/ocp-x86_64/php/imagestreams/php-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/python/imagestreams/python-rhel7.json
  tmp/build/assets/operator/okd-x86_64/php/imagestreams/php-centos7.json
  tmp/build/assets/operator/okd-x86_64/python/imagestreams/python-centos7.json
Labels: approved, lgtm, size/M

#30 run the samples operator on the master node
  deploy/04-operator.yaml
Labels: approved, lgtm, size/XS

#34 recent library updates
  tmp/build/assets/operator/ocp-ppc64le/ruby/imagestreams/ruby-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-example.json
  tmp/build/assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-runtime-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/httpd/imagestreams/httpd-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/nodejs/imagestreams/nodejs-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm70-decisioncentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm70-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm71-decisioncentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm71-decisioncentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm71-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm70-full-persistent.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm70-kieserver-basic-s2i.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm70-kieserver-https-s2i.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm70-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm71-authoring-ha.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm71-authoring.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm71-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm71-prod-immutable-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm71-trial-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam70-businesscentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam70-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-businesscentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-businesscentral-monitoring-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-businesscentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-smartrouter-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-authoring-ha.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-authoring.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-kieserver-externaldb.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-kieserver-mysql.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-kieserver-postgresql.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-prod-immutable-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-prod-immutable-monitor.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-prod.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-sit.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-trial-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/ruby/imagestreams/ruby-rhel7.json
  tmp/build/assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-example.json
  tmp/build/assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-persistent.json
  tmp/build/assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-centos7.json
  tmp/build/assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-runtime-centos7.json
  tmp/build/assets/operator/okd-x86_64/httpd/imagestreams/httpd-centos7.json
  tmp/build/assets/operator/okd-x86_64/nodejs/imagestreams/nodejs-centos7.json
  tmp/build/assets/operator/okd-x86_64/ruby/imagestreams/ruby-centos7.json
Labels: approved, lgtm, size/XXL

#37 minor cluster operator fixes
  Makefile
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/M

#39 add managementstate;
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/L

#40 remove master node selector
  deploy/05-operator.yaml
Labels: approved, lgtm, size/XS
