Repository openshift/cluster-samples-operator, pull requests merged in 2018-09, with the labels that each got.

#7 add dockerfile for building image via PRs
  Dockerfile
  Makefile
  deploy/image-references
  deploy/namespace.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#5 Operator innards 1
  .gitignore
  Dockerfile
  cmd/cluster-samples-operator/main.go
  deploy/cr.yaml
  deploy/openshift-rbac.yaml
  hack/deploy.sh
  images/cluster-samples-operator/Dockerfile
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  tmp/build/Dockerfile
  tmp/build/build.sh
  tmp/build/docker_build.sh
Labels: approved, lgtm, size/XXL

#9 delete spec file, operators not building repos specific rpm
  samples-operator.spec
Labels: approved, lgtm, size/L

#10 clean up owners
  OWNERS
Labels: approved, lgtm, size/XS

#11 deploy: add ordering to manifests that end up in updatepayload
  Dockerfile
  deploy/00-crd.yaml
  deploy/01-namespace.yaml
  deploy/02-rbac.yaml
  deploy/03-operator.yaml
  hack/deploy.sh
Labels: approved, lgtm, size/S

#12 fully add openshift-rbac.yaml on par with other deploy artifacts
  Dockerfile
  deploy/03-openshift-rbac.yaml
  deploy/04-operator.yaml
  hack/deploy.sh
  images/cluster-samples-operator/Dockerfile
Labels: approved, lgtm, size/XS

#13 deploy: add namespace to Role and RoleBindings
  deploy/02-rbac.yaml
Labels: approved, lgtm, size/XS

#15 Group skip dir name
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/L

#16 fix configmap creation; add bad post create cfg change test cases
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/M

#17 bump openshift/library assets
  tmp/build/assets/operator/ocp-ppc64le/ruby/imagestreams/ruby-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/mongodb/templates/mongodb-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/mongodb/templates/mongodb-persistent.json
  tmp/build/assets/operator/ocp-x86_64/mysql/templates/mysql-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/mysql/templates/mysql-persistent.json
  tmp/build/assets/operator/okd-x86_64/mongodb/templates/mongodb-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/mongodb/templates/mongodb-persistent.json
  tmp/build/assets/operator/okd-x86_64/mysql/templates/mysql-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/mysql/templates/mysql-persistent.json
Labels: approved, lgtm, size/M

#18 pick up the Sept 26 updates
  tmp/build/assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-example.json
  tmp/build/assets/operator/ocp-x86_64/cakephp/templates/cakephp-mysql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/dancer/templates/dancer-mysql-example.json
  tmp/build/assets/operator/ocp-x86_64/dancer/templates/dancer-mysql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/django/templates/django-psql-example.json
  tmp/build/assets/operator/ocp-x86_64/django/templates/django-psql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/jenkins/templates/jenkins-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/jenkins/templates/jenkins-persistent.json
  tmp/build/assets/operator/ocp-x86_64/mariadb/templates/mariadb-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/mariadb/templates/mariadb-persistent.json
  tmp/build/assets/operator/ocp-x86_64/mongodb/templates/mongodb-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/mongodb/templates/mongodb-persistent.json
  tmp/build/assets/operator/ocp-x86_64/nodejs/templates/nodejs-mongo-persistent.json
  tmp/build/assets/operator/ocp-x86_64/nodejs/templates/nodejs-mongodb-example.json
  tmp/build/assets/operator/ocp-x86_64/perl/imagestreams/perl-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/postgresql/templates/postgresql-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/postgresql/templates/postgresql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/rails/templates/rails-pgsql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/rails/templates/rails-postgresql-example.json
  tmp/build/assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-example.json
  tmp/build/assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-persistent.json
  tmp/build/assets/operator/okd-x86_64/dancer/templates/dancer-mysql-example.json
  tmp/build/assets/operator/okd-x86_64/dancer/templates/dancer-mysql-persistent.json
  tmp/build/assets/operator/okd-x86_64/django/templates/django-psql-example.json
  tmp/build/assets/operator/okd-x86_64/django/templates/django-psql-persistent.json
  tmp/build/assets/operator/okd-x86_64/jenkins/templates/jenkins-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/jenkins/templates/jenkins-persistent.json
  tmp/build/assets/operator/okd-x86_64/mariadb/templates/mariadb-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/mariadb/templates/mariadb-persistent.json
  tmp/build/assets/operator/okd-x86_64/mongodb/templates/mongodb-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/mongodb/templates/mongodb-persistent.json
  tmp/build/assets/operator/okd-x86_64/nodejs/templates/nodejs-mongo-persistent.json
  tmp/build/assets/operator/okd-x86_64/nodejs/templates/nodejs-mongodb-example.json
  tmp/build/assets/operator/okd-x86_64/perl/imagestreams/perl-centos7.json
  tmp/build/assets/operator/okd-x86_64/postgresql/templates/postgresql-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/postgresql/templates/postgresql-persistent.json
  tmp/build/assets/operator/okd-x86_64/rails/templates/rails-pgsql-persistent.json
  tmp/build/assets/operator/okd-x86_64/rails/templates/rails-postgresql-example.json
Labels: approved, lgtm, size/L

#19 found sdk Get function; use it and delete homegrown version
  pkg/stub/handler.go
Labels: approved, lgtm, size/S

#20 add finalizer processing to ensure we see delete events
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/L
