Repository openshift/cluster-samples-operator, pull requests merged in 2018-11, with the labels that each got.

#41 add samples watches; fix sdk get/upd/create retry; other minor fixes
  cmd/cluster-samples-operator/main.go
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/L

#42 pull in openshift/library updates
  tmp/build/assets/operator/ocp-x86_64/eap-cd/imagestreams/eap-cd-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/eap-cd/templates/eap-cd-amq-persistent-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap-cd/templates/eap-cd-basic-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap-cd/templates/eap-cd-postgresql-persistent-s2i.json
  tmp/build/assets/operator/okd-x86_64/nodejs/imagestreams/nodejs-centos7.json
Labels: approved, lgtm, size/XXL

#43 various fixes to skip processing (change check, removal from skipped …
  pkg/stub/handler.go
Labels: approved, lgtm, size/M

#47 use pull policy always
  deploy/05-operator.yaml
Labels: approved, lgtm, size/XS

#48 add progressing cluster status (imagestreams only)
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/L

#49 temporary dbg for bz1645463
  pkg/stub/handler.go
Labels: approved, lgtm, size/S

#50 more bz1645463 debug
  pkg/stub/handler.go
Labels: approved, lgtm, size/XS

#52 logging cleanup for bz debug, progressing debug
  pkg/stub/handler.go
Labels: approved, lgtm, size/M

#53 bump openshift/library content
  tmp/build/assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-runtime-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/nodejs/imagestreams/nodejs-rhel7.json
  tmp/build/assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-centos7.json
  tmp/build/assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-runtime-centos7.json
  tmp/build/assets/operator/okd-x86_64/nodejs/imagestreams/nodejs-centos7.json
Labels: approved, lgtm, size/M

#55 Fix typo "ppc64l3"
  pkg/stub/handler.go
Labels: approved, lgtm, size/XS

#56 clean up need cred error message
  pkg/stub/handler.go
Labels: approved, lgtm

#57 fix SamplesRegistry serialization
  pkg/apis/samplesoperator/v1alpha1/types.go
Labels: approved, lgtm, size/XS

#54 add e2e tests (along with fixes as a result)
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, lgtm, size/XXL
