Repository openshift/cluster-samples-operator, pull requests merged in 2019-01, with the labels that each got.

#70 Adjust clusteroperator msgs to https://github.com/openshift/cluster-v…
  pkg/apis/samplesoperator/v1alpha1/types.go
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/XL

#72 fixes around imagestream import errors (conditions with items and vic…
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/L

#73 add message in cfg valid condition if override unsupported mgmt state
  pkg/stub/handler.go
Labels: approved, lgtm, size/XS

#75 Renames
  deploy/00-crd.yaml
  deploy/03-rbac.yaml
  deploy/cr.yaml
  hack/codegen/update-generated.sh
  pkg/apis/samples/v1/doc.go
  pkg/apis/samples/v1/register.go
  pkg/apis/samples/v1/types.go
  pkg/apis/samples/v1/zz_generated.deepcopy.go
  pkg/apis/samplesresource/v1alpha1/doc.go
  pkg/client/listers.go
  pkg/generated/clientset/versioned/clientset.go
  pkg/generated/clientset/versioned/fake/clientset_generated.go
  pkg/generated/clientset/versioned/fake/register.go
  pkg/generated/clientset/versioned/scheme/register.go
  pkg/generated/clientset/versioned/typed/samples/v1/config.go
  pkg/generated/clientset/versioned/typed/samples/v1/doc.go
  pkg/generated/clientset/versioned/typed/samples/v1/fake/doc.go
  pkg/generated/clientset/versioned/typed/samples/v1/fake/fake_config.go
  pkg/generated/clientset/versioned/typed/samples/v1/fake/fake_samples_client.go
  pkg/generated/clientset/versioned/typed/samples/v1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/samples/v1/samples_client.go
  pkg/generated/clientset/versioned/typed/samplesresource/v1alpha1/fake/fake_samplesresource.go
  pkg/generated/clientset/versioned/typed/samplesresource/v1alpha1/fake/fake_samplesresource_client.go
  pkg/generated/clientset/versioned/typed/samplesresource/v1alpha1/generated_expansion.go
  pkg/generated/clientset/versioned/typed/samplesresource/v1alpha1/samplesresource.go
  pkg/generated/clientset/versioned/typed/samplesresource/v1alpha1/samplesresource_client.go
  pkg/generated/informers/externalversions/factory.go
  pkg/generated/informers/externalversions/generic.go
  pkg/generated/informers/externalversions/samples/interface.go
  pkg/generated/informers/externalversions/samples/v1/config.go
  pkg/generated/informers/externalversions/samples/v1/interface.go
  pkg/generated/informers/externalversions/samplesresource/v1alpha1/samplesresource.go
  pkg/generated/listers/samples/v1/config.go
  pkg/generated/listers/samples/v1/expansion_generated.go
  pkg/generated/listers/samplesresource/v1alpha1/expansion_generated.go
  pkg/generated/listers/samplesresource/v1alpha1/samplesresource.go
  pkg/operator/bootstrap.go
  pkg/operator/controller.go
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, lgtm, size/XXL

#78 godoc/value consistency fixes for types via wewang/bparees
  pkg/apis/samples/v1/types.go
Labels: approved, lgtm, size/XS

#76 readme update for rename, recent evolution; cluster operator conditio…
  README.md
  pkg/apis/samples/v1/types.go
  pkg/stub/handler.go
Labels: approved, lgtm, size/M

#77 Prevent usr upd status
  deploy/00-crd.yaml
  deploy/03-rbac.yaml
  pkg/apis/samples/v1/types.go
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/L

#79 fix import img err detect when len(status) < len(spec); minor fixes o…
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/L

#80 Restruct and skip clear imp err
  README.md
  pkg/apis/samples/v1/types.go
  pkg/stub/config.go
  pkg/stub/files.go
  pkg/stub/finalizer.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/interfaces.go
  pkg/stub/secrets.go
  pkg/stub/templates.go
Labels: approved, lgtm, size/XXL

#82 set cpu requests per new tech direction
  deploy/05-operator.yaml
Labels: approved, lgtm, size/XS

#84 pick up recent openshift library changes
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm71-decisioncentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm71-decisioncentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm71-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm71-optaweb-employee-rostering-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm72-decisioncentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm72-decisioncentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm72-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm72-optaweb-employee-rostering-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-authoring-ha.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-authoring.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-optaweb-employee-rostering-trial-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-prod-immutable-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-trial-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-businesscentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-businesscentral-monitoring-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-businesscentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam71-smartrouter-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-businesscentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-businesscentral-monitoring-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-businesscentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-smartrouter-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam71-prod.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-authoring-ha.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-authoring.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-kieserver-externaldb.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-kieserver-mysql.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-kieserver-postgresql.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-prod-immutable-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-prod-immutable-monitor.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-prod.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-trial-ephemeral.json
Labels: approved, lgtm, size/XXL

#85 add image refs, env vars, so we can get jenkins images from payload
  deploy/05-operator.yaml
  deploy/image-references
  pkg/stub/interfaces.go
  pkg/stub/jenkins.go
Labels: approved, lgtm, size/M

#87 force operator onto master nodes
  deploy/05-operator.yaml
Labels: approved, lgtm, size/XS

#89 Move the cli image stream into samples operator
  Dockerfile
  Dockerfile.rhel7
  deploy/06-openshift-imagestreams.yaml
  deploy/image-references
Labels: approved, lgtm, size/M
