Repository openshift/cluster-samples-operator, pull requests merged in 2019-05, with the labels that each got.

#140 reduce gets on samples operator config object when processing template/imagestream events
  pkg/operator/controller.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/interfaces.go
  pkg/stub/templates.go
Labels: approved, lgtm, size/M

#142 Fix tolerations
  manifests/06-operator.yaml
Labels: approved, lgtm, size/S

#145 fix clusteroperator related-objects, set with updatestatus vs. create
  pkg/operatorstatus/operatorstatus.go
Labels: approved, lgtm, size/S

#147 update Makefile to golang 1.11 for local dev (openshift/release confi…
  Dockerfile
Labels: approved, lgtm, size/XS

#146 Bug 1707834: use informer cache instead of api server for GETs on tem…
  pkg/operator/controller.go
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/interfaces.go
  pkg/stub/secrets.go
  pkg/stub/templates.go
Labels: approved, lgtm, size/L

#148 Bug 1705753: some godoc changes on the config CRD type for better oc explain behavior
  manifests/00-crd.yaml
  pkg/apis/samples/v1/types.go
Labels: approved, lgtm, size/S

#149 first 4.2 bump in samples content
  tmp/build/assets/operator/ocp-x86_64/3scale/imagestreams/apicast-gateway.json
  tmp/build/assets/operator/ocp-x86_64/3scale/templates/3scale-gateway.json
  tmp/build/assets/operator/ocp-x86_64/datavirt/templates/datavirt64-basic-s2i.json
  tmp/build/assets/operator/ocp-x86_64/datavirt/templates/datavirt64-extensions-support-s2i.json
  tmp/build/assets/operator/ocp-x86_64/datavirt/templates/datavirt64-secure-s2i.json
  tmp/build/assets/operator/ocp-x86_64/fis/imagestreams/apicurito-ui-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/fis/imagestreams/fuse-apicurito-generator-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/fis/imagestreams/fuse7-console-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/fis/imagestreams/fuse7-eap-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/fis/imagestreams/fuse7-java-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/fis/imagestreams/fuse7-karaf-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/fis/templates/apicurito.json
  tmp/build/assets/operator/ocp-x86_64/fis/templates/fuse73-console.json
  tmp/build/assets/operator/ocp-x86_64/fis/templates/s2i-fuse73-spring-boot-camel-rest-3scale.json
  tmp/build/assets/operator/ocp-x86_64/fis/templates/s2i-fuse73-spring-boot-camel-xml.json
  tmp/build/assets/operator/ocp-x86_64/fis/templates/s2i-fuse73-spring-boot-camel.json
  tmp/build/assets/operator/ocp-x86_64/java/imagestreams/java-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/java/imagestreams/openjdk-11-rhel7-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/java/imagestreams/redhat-openjdk18-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/java/templates/openjdk-web-basic-s2i.json
  tmp/build/assets/operator/ocp-x86_64/mongodb/templates/mongodb-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/mongodb/templates/mongodb-persistent.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm73-decisioncentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm73-decisioncentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm73-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm73-optaweb-employee-rostering-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm73-authoring-ha.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm73-authoring.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm73-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm73-optaweb-employee-rostering.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm73-prod-immutable-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm73-trial-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam73-businesscentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam73-businesscentral-monitoring-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam73-businesscentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam73-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam73-smartrouter-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-authoring-ha.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-authoring.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-kieserver-externaldb.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-kieserver-mysql.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-kieserver-postgresql.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-managed.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-prod-immutable-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-prod-immutable-monitor.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-prod.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam73-trial-ephemeral.json
Labels: approved, lgtm, size/XXL
