Repository openshift/cluster-samples-operator, pull requests merged in 2019-08, with the labels that each got.

#162 Bug 1734627: preserve deleted EOL ISTs on upgrade
  pkg/stub/imagestreams.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#163 Bug 1735711: lock down timing windows when deletes of the config object come in du…
  pkg/stub/handler.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#165 Bug 1738256: report clusteroperator degraded if image import persists for 2 hours
  pkg/apis/samples/v1/types.go
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#167 Bug 1739214: set degraded reason/msg on cluster operator obj when degraded==true
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/handler_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#169 Bug 1735711: another concurrent delete/images still importing fix - cover window a…
  pkg/stub/handler.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#170 Add baremetal-installer to image-references
  manifests/image-references
Labels: approved, lgtm, size/XS

#171 Revert "Add baremetal-installer to image-references"
  manifests/image-references
Labels: approved, lgtm, size/XS

#173 add registry.svc.ci.openshift.org to the list of overridable registri…
  pkg/stub/imagestreams.go
Labels: approved, lgtm, size/XS

#174 Add reference to baremetal-installer
  manifests/image-references
Labels: approved, lgtm, size/XS

#175 Bug 1742907: Degraded missing reason detail 41
  pkg/apis/samples/v1/types.go
  pkg/operatorstatus/operatorstatus.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#177 Bug 1744071: allow override of jenkins* imagestream registries for disconnected/mi…
  pkg/stub/imagestreams.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#179 Bug 1746342: clean up available/progressing/degraded, including new msg/reason, wh…
  pkg/apis/samples/v1/types.go
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/handler_test.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#180 add list of imagestreams failing import to progressing/degraded detailed message
  pkg/apis/samples/v1/types.go
Labels: approved, lgtm, size/XS
