Repository openshift/cluster-samples-operator, pull requests merged in 2019-02, with the labels that each got.

#88 pull in openshift/library updates, including jenkins agent streams
  pkg/apis/samples/v1/types.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/jenkins.go
  tmp/build/assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap72-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-basic-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-https-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-mongodb-persistent-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-mongodb-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-mysql-persistent-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-mysql-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-postgresql-persistent-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-postgresql-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-sso-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap/templates/eap72-third-party-db-s2i.json
  tmp/build/assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-maven-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-nodejs-rhel7.json
  tmp/build/assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-agent-maven-centos7.json
  tmp/build/assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-agent-nodejs-centos7.json
  tmp/build/assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-centos7.json
Labels: approved, lgtm, size/L

#81 force default to rhel and registry to old redhat one
  README.md
  deploy/07-clusteroperator.yaml
  deploy/clusteroperator-crd.yaml
  deploy/cr.yaml
  pkg/apis/samples/v1/types.go
  pkg/cache/deletes.go
  pkg/cache/upserts.go
  pkg/operator/controller.go
  pkg/stub/config.go
  pkg/stub/files.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/retry.go
  pkg/stub/secrets.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, lgtm, size/XXL

#91 complete condition naming cleanup
  README.md
  pkg/apis/samples/v1/types.go
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, size/S

#93 do not require credentials if mgmt state removed/unmanaged
  pkg/apis/samples/v1/types.go
Labels: approved, lgtm, size/XS

#94 consolidate e2e into 1 package, ensure that do not run tests in paral…
  Makefile
  test/e2e/cluster_samples_operator_test.go
  test/e2e/main_test.go
Labels: approved, lgtm, size/S

#92 normal arch array to string in cannot change arch warning msg
  pkg/stub/config.go
Labels: approved, lgtm, size/XS

#90 rename clusteroperator resource, align manifests dir name w/ other operators
  Dockerfile
  Dockerfile.rhel7
  manifests/00-crd.yaml
  manifests/01-namespace.yaml
  manifests/02-sa.yaml
  manifests/03-rbac.yaml
  manifests/04-openshift-rbac.yaml
  manifests/05-operator.yaml
  manifests/06-openshift-imagestreams.yaml
  manifests/07-clusteroperator.yaml
  manifests/image-references
  pkg/operatorstatus/operatorstatus.go
Labels: approved, lgtm, size/XS

#98 copy pull images secret form kube-system by default
  manifests/08-kube-system-rbac.yaml
  pkg/stub/handler.go
  pkg/stub/secrets.go
Labels: approved, lgtm, size/M

#95 rebuild filesystem map on config change
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/interfaces.go
  pkg/stub/jenkins.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, lgtm, size/M

#101 re-order manifests for kube-system rbac is created before operator de…
  manifests/05-kube-system-rbac.yaml
  manifests/07-operator.yaml
  manifests/08-clusteroperator.yaml
Labels: approved, lgtm, size/XS

#102 bump openshift/library import (pick up jenkins-1 removal)
  tmp/build/assets/operator/ocp-x86_64/dotnet/templates/dotnet-pgsql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel7.json
  tmp/build/assets/operator/okd-x86_64/dotnet/templates/dotnet-pgsql-persistent.json
  tmp/build/assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-centos7.json
Labels: approved, lgtm, size/M

#99 Kube system cleanup
  README.md
  manifests/05-kube-system-rbac.yaml
  pkg/operator/controller.go
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/secrets.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, lgtm, size/L

#104 need some more verification of operator processing of config change i…
  pkg/stub/handler.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, lgtm, size/L

#105 bump cache window to account for timing data from initial installs
  pkg/cache/upserts.go
Labels: approved, lgtm, size/XS

#106 change operator ID from 'instance' to 'cluster'
  README.md
  pkg/apis/samples/v1/types.go
Labels: approved, lgtm, size/XS

#103 remove okd/centos
  README.md
  pkg/apis/samples/v1/types.go
  pkg/stub/config.go
  pkg/stub/files.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  test/e2e/cluster_samples_operator_test.go
  tmp/build/assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-example.json
  tmp/build/assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-persistent.json
  tmp/build/assets/operator/okd-x86_64/dancer/templates/dancer-mysql-example.json
  tmp/build/assets/operator/okd-x86_64/dancer/templates/dancer-mysql-persistent.json
  tmp/build/assets/operator/okd-x86_64/django/templates/django-psql-example.json
  tmp/build/assets/operator/okd-x86_64/django/templates/django-psql-persistent.json
  tmp/build/assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-centos7.json
  tmp/build/assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-runtime-centos7.json
  tmp/build/assets/operator/okd-x86_64/dotnet/templates/dotnet-example.json
  tmp/build/assets/operator/okd-x86_64/dotnet/templates/dotnet-pgsql-persistent.json
  tmp/build/assets/operator/okd-x86_64/httpd/imagestreams/httpd-centos7.json
  tmp/build/assets/operator/okd-x86_64/httpd/templates/httpd-example.json
  tmp/build/assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-agent-maven-centos7.json
  tmp/build/assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-agent-nodejs-centos7.json
  tmp/build/assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-centos7.json
  tmp/build/assets/operator/okd-x86_64/jenkins/templates/jenkins-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/jenkins/templates/jenkins-persistent.json
  tmp/build/assets/operator/okd-x86_64/mariadb/imagestreams/mariadb-centos7.json
  tmp/build/assets/operator/okd-x86_64/mariadb/templates/mariadb-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/mariadb/templates/mariadb-persistent.json
  tmp/build/assets/operator/okd-x86_64/mongodb/imagestreams/mongodb-centos7.json
  tmp/build/assets/operator/okd-x86_64/mongodb/templates/mongodb-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/mongodb/templates/mongodb-persistent.json
  tmp/build/assets/operator/okd-x86_64/mysql/imagestreams/mysql-centos7.json
  tmp/build/assets/operator/okd-x86_64/mysql/templates/mysql-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/mysql/templates/mysql-persistent.json
  tmp/build/assets/operator/okd-x86_64/nginx/imagestreams/nginx-centos7.json
  tmp/build/assets/operator/okd-x86_64/nginx/templates/nginx-example.json
  tmp/build/assets/operator/okd-x86_64/nodejs/imagestreams/nodejs-centos7.json
  tmp/build/assets/operator/okd-x86_64/nodejs/templates/nodejs-mongo-persistent.json
  tmp/build/assets/operator/okd-x86_64/nodejs/templates/nodejs-mongodb-example.json
  tmp/build/assets/operator/okd-x86_64/perl/imagestreams/perl-centos7.json
  tmp/build/assets/operator/okd-x86_64/php/imagestreams/php-centos7.json
  tmp/build/assets/operator/okd-x86_64/postgresql/imagestreams/postgresql-centos7.json
  tmp/build/assets/operator/okd-x86_64/postgresql/templates/postgresql-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/postgresql/templates/postgresql-persistent.json
  tmp/build/assets/operator/okd-x86_64/python/imagestreams/python-centos7.json
  tmp/build/assets/operator/okd-x86_64/rails/templates/rails-pgsql-persistent.json
  tmp/build/assets/operator/okd-x86_64/rails/templates/rails-postgresql-example.json
  tmp/build/assets/operator/okd-x86_64/redis/imagestreams/redis-centos7.json
  tmp/build/assets/operator/okd-x86_64/redis/templates/redis-ephemeral.json
  tmp/build/assets/operator/okd-x86_64/redis/templates/redis-persistent.json
  tmp/build/assets/operator/okd-x86_64/ruby/imagestreams/ruby-centos7.json
  tmp/build/assets/operator/okd-x86_64/wildfly/imagestreams/wildfly-centos7.json
  tmp/build/library-sync.sh
Labels: approved, lgtm, size/XXL

#110 Remove ppc
  README.md
  pkg/apis/samples/v1/types.go
  pkg/stub/config.go
  pkg/stub/files.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  test/e2e/cluster_samples_operator_test.go
  tmp/build/assets/operator/ocp-ppc64le/ruby/imagestreams/ruby-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/eap-cd/imagestreams/eap-cd-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/eap-cd/templates/eap-cd-basic-s2i.json
  tmp/build/assets/operator/ocp-x86_64/eap-cd/templates/eap-cd-postgresql-persistent-s2i.json
  tmp/build/assets/operator/ocp-x86_64/mysql/imagestreams/mysql-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/php/imagestreams/php-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm72-decisioncentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm72-decisioncentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm72-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/imagestreams/rhdm72-optaweb-employee-rostering-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-authoring-ha.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-authoring.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-optaweb-employee-rostering-trial-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-prod-immutable-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhdm/templates/rhdm72-trial-ephemeral.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-businesscentral-indexing-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-businesscentral-monitoring-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-businesscentral-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-kieserver-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/imagestreams/rhpam72-smartrouter-openshift-rhel7.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-authoring-ha.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-authoring.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-kieserver-externaldb.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-kieserver-mysql.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-kieserver-postgresql.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-prod-immutable-kieserver.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-prod-immutable-monitor.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-prod.json
  tmp/build/assets/operator/ocp-x86_64/rhpam/templates/rhpam72-trial-ephemeral.json
  tmp/build/library-sync.sh
Labels: approved, lgtm, size/XL

#109 Upsert opts
  pkg/cache/upserts.go
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/imagestreams.go
Labels: approved, lgtm, size/L

#112 insure clayton special imagestreams created after secret copied
  manifests/06-operator.yaml
  manifests/07-clusteroperator.yaml
  manifests/08-openshift-imagestreams.yaml
Labels: approved, lgtm, size/XS

#113 use pumped up rate limiter, shave 30 seconds from startup creates
  pkg/stub/interfaces.go
Labels: approved, lgtm, size/XS

#111 Goto tbr
  README.md
  pkg/apis/samples/v1/types.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
Labels: approved, lgtm, size/L

#115 Cvo tweaks
  pkg/apis/samples/v1/types.go
Labels: approved, lgtm, size/S

#116 Add must-gather image reference and ImageStream
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, lgtm, size/S
