Repository openshift/cluster-samples-operator, pull requests merged in 2019-04, with the labels that each got.

#130 BUG 1697644: operator: use openshift-config/pull-secret to fetch the pull secret
  manifests/05-kube-system-rbac.yaml
  pkg/operator/controller.go
  pkg/stub/handler.go
  pkg/stub/secrets.go
Labels: approved, lgtm, size/S

#131 Add the cli-artifacts and installer-artifacts images to the payload
  manifests/06-operator.yaml
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, lgtm, size/M

#137 simplify, be explicit, on imagestream update reporting; don't miss up…
  pkg/stub/handler.go
  pkg/stub/imagestreams.go
Labels: approved, lgtm, size/M

#139 Add node-selector annotation to namespace
  manifests/01-namespace.yaml
Labels: approved, lgtm, size/XS

#138 remove extra get on crd during imagestream processing (a conflict win…
  pkg/stub/imagestreams.go
Labels: approved, lgtm, size/XS
