Repository openshift/cluster-samples-operator, pull requests merged in 2020-06, with the labels that each got.

#278 Standardize go imports
  cmd/cluster-samples-operator/main.go
  pkg/client/listers.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/operator/controller.go
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/config.go
  pkg/stub/files.go
  pkg/stub/finalizer.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/interfaces.go
  pkg/stub/jenkins.go
  pkg/stub/retry.go
  pkg/stub/templates.go
  pkg/util/util.go
  test/e2e/cluster_samples_operator_test.go
  test/e2e/main_test.go
Labels: approved, lgtm

#282 [release-4.4] Bug 1842560: improve reason text on degraded condition
  pkg/stub/config.go
  pkg/stub/handler_test.go
  pkg/util/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#279 Bug 1835995: ensure s390/ppc64le platforms bootstrap as removed following upgrade
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/imagestreams.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#284 pull in sso compatibility fixes for 4.5 and above
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso72-x509-https.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso73-ocp4-x509-https.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso73-ocp4-x509-mysql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso73-ocp4-x509-postgresql-persistent.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso74-ocp4-x509-https.json
  tmp/build/assets/operator/ocp-x86_64/sso/templates/sso74-ocp4-x509-postgresql-persistent.json
Labels: approved, lgtm

#285 Bug 1835996: ensure s390/ppc64le platforms bootstrap as removed following upgrade
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/imagestreams.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#287 Fix a typo
  pkg/stub/templates.go
Labels: approved, lgtm, ok-to-test

#288 Fix samplesRegistry replacement in imageStreams when using paths
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
Labels: approved, lgtm

#298 Update file/folder removal for library transition to golang
  tmp/build/library-sync.sh
Labels: approved, lgtm

#290 [BUILD-92] add import retry count into metrics
  pkg/metrics/metrics.go
  pkg/metrics/server.go
  pkg/metrics/server_test.go
  pkg/stub/imagestreams.go
Labels: approved, lgtm
