Repository openshift/cluster-samples-operator, pull requests merged in 2020-08, with the labels that each got.

#310 Update OKD contents sync script
  assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-example.json
  assets/operator/okd-x86_64/cakephp/templates/cakephp-mysql-persistent.json
  assets/operator/okd-x86_64/dancer/templates/dancer-mysql-example.json
  assets/operator/okd-x86_64/dancer/templates/dancer-mysql-persistent.json
  assets/operator/okd-x86_64/django/templates/django-psql-example.json
  assets/operator/okd-x86_64/django/templates/django-psql-persistent.json
  assets/operator/okd-x86_64/dotnet/templates/dotnet-example.json
  assets/operator/okd-x86_64/dotnet/templates/dotnet-pgsql-persistent.json
  assets/operator/okd-x86_64/httpd/templates/httpd-example.json
  assets/operator/okd-x86_64/jenkins/templates/jenkins-ephemeral-monitored.json
  assets/operator/okd-x86_64/jenkins/templates/jenkins-ephemeral.json
  assets/operator/okd-x86_64/jenkins/templates/jenkins-persistent-monitored.json
  assets/operator/okd-x86_64/jenkins/templates/jenkins-persistent.json
  assets/operator/okd-x86_64/mariadb/templates/mariadb-ephemeral.json
  assets/operator/okd-x86_64/mariadb/templates/mariadb-persistent.json
  assets/operator/okd-x86_64/mongodb/templates/mongodb-ephemeral.json
  assets/operator/okd-x86_64/mongodb/templates/mongodb-persistent.json
  assets/operator/okd-x86_64/mysql/templates/mysql-ephemeral.json
  assets/operator/okd-x86_64/mysql/templates/mysql-persistent.json
  assets/operator/okd-x86_64/nginx/templates/nginx-example.json
  assets/operator/okd-x86_64/nodejs/templates/nodejs-mongo-persistent.json
  assets/operator/okd-x86_64/nodejs/templates/nodejs-mongodb-example.json
  assets/operator/okd-x86_64/postgresql/templates/postgresql-ephemeral.json
  assets/operator/okd-x86_64/postgresql/templates/postgresql-persistent.json
  assets/operator/okd-x86_64/rails/templates/rails-pgsql-persistent.json
  assets/operator/okd-x86_64/rails/templates/rails-postgresql-example.json
  assets/operator/okd-x86_64/redis/templates/redis-ephemeral.json
  assets/operator/okd-x86_64/redis/templates/redis-persistent.json
  library-sync.sh
Labels: approved, lgtm

#311 Bug 1863014: fixing typo in the registry.redhat.io fqdn
  manifests/010-prometheus-rules.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#318 Bug 1872080: add new okd e2e to validate okd vs. ocp content is installed
  Makefile
  test/e2e/cluster_samples_operator_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
