Repository openshift/cluster-samples-operator, pull requests merged in 2020-12, with the labels that each got.

#343 Annotate manifests for single-node-developer cluster profile
  manifests/01-namespace.yaml
  manifests/010-prometheus-rules.yaml
  manifests/02-sa.yaml
  manifests/03-rbac-proxies-role-binding.yaml
  manifests/03-rbac-proxies-role.yaml
  manifests/03-rbac.yaml
  manifests/04-openshift-rbac.yaml
  manifests/05-kube-system-rbac.yaml
  manifests/06-metricsservice.yaml
  manifests/06-operator.yaml
  manifests/06-servicemonitor.yaml
  manifests/07-clusteroperator.yaml
  manifests/08-openshift-imagestreams.yaml
  manifests/09-servicemonitor-rbac.yaml
Labels: approved, lgtm

#345 more README updates/fixes
  README.md
Labels: approved, lgtm

#347 more readme corrections stemming from skills transfer work
  README.md
Labels: approved, lgtm

#348 Bug 1905319: request required minimal mem resource per openshift conventions
  manifests/06-operator.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#350 Bug 1766287: Improve usability of hello-openshift imagestream
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
