Repository openshift/cluster-samples-operator, pull requests merged in 2020-04, with the labels that each got.

#248 Bug 1805250: manifests: add openshift/oauth-proxy:v4.4 image
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#234 [release-4.2] Bug 1805615: no longer gate removed processing when imagestreams in progress
  pkg/apis/samples/v1/types.go
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#236 create metric/alert around sample boostrapping as removed for inacces…
  manifests/010-prometheus-rules.yaml
  pkg/metrics/metrics.go
  pkg/metrics/server.go
  pkg/metrics/server_test.go
  pkg/operatorstatus/operatorstatus.go
Labels: approved, lgtm, size/M

#258 handle concurrent metrics_test.go hiccups
  pkg/metrics/server_test.go
Labels: approved, lgtm

#256 Bug 1818476: copy install pull secret when boostrapped as removed
  pkg/stub/handler_test.go
  pkg/stub/secrets.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#259 more work around metric unit tests flakes
  pkg/metrics/server_test.go
Labels: approved, lgtm

#260 Bug 1822381: revert pr 177; no override jenkins* registry hosts for mirrors
  pkg/stub/imagestreams.go
Labels: approved, bugzilla/valid-bug, lgtm

#255 Add component to OWNERS
  OWNERS
Labels: approved, lgtm

#249 remove pull secret copy, defer to image registry
  Makefile
  pkg/client/listers.go
  pkg/metrics/metrics.go
  pkg/operator/controller.go
  pkg/stub/config.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/interfaces.go
  pkg/stub/secrets.go
  pkg/util/util.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, lgtm

#264 Bug 1825774: add back missing parts to make openshift-config namespace secret list…
  pkg/operator/controller.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, lgtm

#265 Bug 1828065: correctly handle removed templates watch events as part of an upgrade
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#268 Bug 1829874: update Dockerfile.rhel builder image to line up with art/brew/osbs
  Dockerfile.rhel7
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
