Repository openshift/cluster-samples-operator, pull requests merged in 2020-03, with the labels that each got.

#237 Revert "add imagestream for oauthproxy image"
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#238 Revert "add imagestream for oauthproxy image"
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#240 Bug 1811143: purge removed imagestreams as a part of upgrade from progessing/impor…
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/templates.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#241 manifests: add openshift/oauth-proxy:v4.4 image
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, lgtm, size/S

#246 Bug 1813175: abort metrics in general if removed/unmanaged
  pkg/metrics/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm

#247 Bug 1812554: manifests: add openshift/oauth-proxy:v4.4 image
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#252 manifests: Add the new 'tools' image as an image stream for debug
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, lgtm
