Repository openshift/cluster-samples-operator, pull requests merged in 2020-11, with the labels that each got.

#313 BUILD-125: move imagestream tracking out of operator config object
  README.md
  pkg/cache/upserts.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/operatorstatus/operatorstatus.go
  pkg/stub/config.go
  pkg/stub/configmap.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/templates.go
  pkg/util/util.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, lgtm

#338 set progressing false on imagestream events as well if no active streams
  README.md
  pkg/stub/config.go
  pkg/stub/configmap.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, lgtm

#340 Bug 1898745: actually set imagestreams in progress to false in imagestream event path
  pkg/stub/imagestreams.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#341 Bug 1898745: deprecate ImageChangesInProgress, make sure it stays false
  README.md
  pkg/stub/config.go
  pkg/stub/configmap.go
  pkg/stub/files.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#342 add 'single-node-production-edge' annotations to CVO manifests
  manifests/01-namespace.yaml
  manifests/010-prometheus-rules.yaml
  manifests/02-sa.yaml
  manifests/03-rbac-proxies-role-binding.yaml
  manifests/03-rbac-proxies-role.yaml
  manifests/03-rbac.yaml
  manifests/04-openshift-rbac.yaml
  manifests/05-kube-system-rbac.yaml
  manifests/06-metricsservice.yaml
  manifests/06-operator.yaml
  manifests/06-servicemonitor.yaml
  manifests/07-clusteroperator.yaml
  manifests/08-openshift-imagestreams.yaml
  manifests/09-servicemonitor-rbac.yaml
Labels: approved, do-not-merge/hold, lgtm
