Repository openshift/cluster-samples-operator, pull requests merged in 2021-04, with the labels that each got.

#366 Add management workload annotations
  manifests/01-namespace.yaml
  manifests/06-operator-ibm-cloud-managed.yaml
  manifests/06-operator.yaml
Labels: approved, lgtm

#368 Bug 1948782: revert single-node-production-edge annotation
  manifests/01-namespace.yaml
  manifests/010-prometheus-rules.yaml
  manifests/02-sa.yaml
  manifests/03-rbac-proxies-role-binding.yaml
  manifests/03-rbac-proxies-role.yaml
  manifests/03-rbac.yaml
  manifests/04-openshift-rbac.yaml
  manifests/05-kube-system-rbac.yaml
  manifests/06-metricsservice.yaml
  manifests/06-operator.yaml
  manifests/06-servicemonitor.yaml
  manifests/07-clusteroperator.yaml
  manifests/08-openshift-imagestreams.yaml
  manifests/09-servicemonitor-rbac.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#360 Bug 1950236: OKD: replace some docker.io images with quay.io
  assets/operator/okd-x86_64/nginx/imagestreams/nginx-centos.json
  assets/operator/okd-x86_64/ruby/imagestreams/ruby-centos.json
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#369 Bug 1949481: add DeepCopy to avoid SharedInformer cache mutation
  pkg/metrics/metrics.go
  pkg/stub/files.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/interfaces.go
  pkg/stub/templates.go
  pkg/util/util.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#370 Bug 1950808: add DeepCopy to avoid SharedInformer cache mutation
  pkg/metrics/metrics.go
  pkg/stub/files.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/interfaces.go
  pkg/stub/templates.go
  pkg/util/util.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved

#372 Rename workload annotations
  manifests/06-operator-ibm-cloud-managed.yaml
  manifests/06-operator.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#371 Bug 1950809: add DeepCopy to avoid SharedInformer cache mutation
  pkg/metrics/metrics.go
  pkg/stub/files.go
  pkg/stub/handler.go
  pkg/stub/handler_test.go
  pkg/stub/imagestreams.go
  pkg/stub/interfaces.go
  pkg/stub/templates.go
  pkg/util/util.go
  test/e2e/cluster_samples_operator_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm, qe-approved
