Repository openshift/cluster-samples-operator, pull requests merged in 2022-06, with the labels that each got.

#429 Bug 2095256: Samples Owner needs to be Updated
  OWNERS
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-high

#431 Bug 2086086: Update Cluster Sample Operator dependencies and libraries for OCP 4.11
  assets/operator/ocp-ppc64le/eap/imagestreams/jboss-eap-xp3-openjdk11-openshift-rhel8.json
  assets/operator/ocp-ppc64le/eap/imagestreams/jboss-eap-xp3-openjdk11-runtime-openshift-rhel8.json
  assets/operator/ocp-ppc64le/eap/imagestreams/jboss-eap74-openjdk11-openshift-rhel8.json
  assets/operator/ocp-ppc64le/eap/imagestreams/jboss-eap74-openjdk11-runtime-openshift-rhel8.json
  assets/operator/ocp-ppc64le/eap/templates/eap-xp3-basic-s2i.json
  assets/operator/ocp-ppc64le/eap/templates/eap74-basic-s2i.json
  assets/operator/ocp-ppc64le/eap/templates/eap74-https-s2i.json
  assets/operator/ocp-ppc64le/eap/templates/eap74-sso-s2i.json
  assets/operator/ocp-s390x/eap/imagestreams/jboss-eap-xp3-openjdk11-openshift-rhel8.json
  assets/operator/ocp-s390x/eap/imagestreams/jboss-eap-xp3-openjdk11-runtime-openshift-rhel8.json
  assets/operator/ocp-s390x/eap/imagestreams/jboss-eap74-openjdk11-openshift-rhel8.json
  assets/operator/ocp-s390x/eap/imagestreams/jboss-eap74-openjdk11-runtime-openshift-rhel8.json
  assets/operator/ocp-s390x/eap/templates/eap-xp3-basic-s2i.json
  assets/operator/ocp-s390x/eap/templates/eap74-basic-s2i.json
  assets/operator/ocp-s390x/eap/templates/eap74-https-s2i.json
  assets/operator/ocp-s390x/eap/templates/eap74-sso-s2i.json
  assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap-xp3-openjdk11-openshift-rhel8.json
  assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap-xp3-openjdk11-runtime-openshift-rhel8.json
  assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap74-openjdk11-openshift-rhel8.json
  assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap74-openjdk11-runtime-openshift-rhel8.json
  assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap74-openjdk8-openshift-rhel7.json
  assets/operator/ocp-x86_64/eap/imagestreams/jboss-eap74-openjdk8-runtime-openshift-rhel7.json
  assets/operator/ocp-x86_64/eap/templates/eap-xp3-basic-s2i.json
  assets/operator/ocp-x86_64/eap/templates/eap74-basic-s2i.json
  assets/operator/ocp-x86_64/eap/templates/eap74-https-s2i.json
  assets/operator/ocp-x86_64/eap/templates/eap74-sso-s2i.json
  assets/operator/ocp-x86_64/fis/imagestreams/fis-java-openshift-rhel7.json
  assets/operator/ocp-x86_64/fis/imagestreams/fis-karaf-openshift-rhel7.json
  assets/operator/ocp-x86_64/fis/imagestreams/jboss-fuse70-console-rhel7.json
  assets/operator/ocp-x86_64/fis/imagestreams/jboss-fuse70-eap-openshift-rhel7.json
  assets/operator/ocp-x86_64/fis/imagestreams/jboss-fuse70-java-openshift-rhel7.json
  assets/operator/ocp-x86_64/fis/imagestreams/jboss-fuse70-karaf-openshift-rhel7.json
  assets/operator/okd-x86_64/wildfly/imagestreams/wildfly-centos7.json
  assets/operator/okd-x86_64/wildfly/imagestreams/wildfly-runtime-centos7.json
  assets/operator/okd-x86_64/wildfly/templates/wildfly-s2i-chained-build-template.json
Labels: approved, lgtm, ok-to-test, bugzilla/valid-bug, bugzilla/severity-high

#432 update jenkins CPaaS image refs prior to 4.11 GA
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-agent-base-centos.json
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#433 Bug 2086086: Update Cluster Sample Operator dependencies and libraries for OCP 4.11
  assets/operator/ocp-x86_64/amq/imagestreams/jboss-amq-63-rhel7.json
  assets/operator/ocp-x86_64/amq/templates/amq63-basic.json
  assets/operator/ocp-x86_64/amq/templates/amq63-persistent-ssl.json
  assets/operator/ocp-x86_64/amq/templates/amq63-persistent.json
  assets/operator/ocp-x86_64/amq/templates/amq63-ssl.json
  assets/operator/ocp-x86_64/datagrid/imagestreams/jboss-datagrid73-openshift-rhel7.json
  assets/operator/ocp-x86_64/datagrid/templates/cache-service.json
  assets/operator/ocp-x86_64/datagrid/templates/datagrid-service.json
  assets/operator/ocp-x86_64/fis/imagestreams/apicurito-ui-rhel7.json
  assets/operator/ocp-x86_64/fis/imagestreams/fuse-apicurito-generator-rhel7.json
  assets/operator/ocp-x86_64/fis/imagestreams/fuse7-console-rhel7.json
  assets/operator/ocp-x86_64/fis/templates/apicurito.json
  assets/operator/ocp-x86_64/fis/templates/fuse710-console.json
  assets/operator/okd-x86_64/modern-webapp/templates/react-web-app-example.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
