Repository openshift/cluster-samples-operator, pull requests merged in 2022-01, with the labels that each got.

#402 Update OWNERS
  OWNERS
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#407 Bug 2027745: Move openshift build-machinery-go dependency
  go.mod
  go.sum
  manifests/06-operator-ibm-cloud-managed.yaml
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/authhandler/authhandler.go
  vendor/golang.org/x/oauth2/go.mod
  vendor/golang.org/x/oauth2/go.sum
  vendor/golang.org/x/oauth2/google/appengine_gen1.go
  vendor/golang.org/x/oauth2/google/appengine_gen2_flex.go
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/err.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/filecredsource.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/sts_exchange.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/urlcredsource.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/google.golang.org/appengine/.travis.yml
  vendor/google.golang.org/appengine/internal/api.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#410 upd rhel7 Dockerfile in case still used for rhel7 worker nodes
  Dockerfile.rhel7
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#411 Bug 2033720: Synching SSO library
  assets/operator/ocp-ppc64le/sso/imagestreams/sso74-openj9-openshift-rhel8.json
  assets/operator/ocp-ppc64le/sso/imagestreams/sso75-openj9-openshift-rhel8.json
  assets/operator/ocp-ppc64le/sso/templates/sso74-openj9-https.json
  assets/operator/ocp-ppc64le/sso/templates/sso74-openj9-ocp4-x509-https.json
  assets/operator/ocp-ppc64le/sso/templates/sso74-openj9-ocp4-x509-postgresql-persistent.json
  assets/operator/ocp-ppc64le/sso/templates/sso74-openj9-postgresql-persistent.json
  assets/operator/ocp-ppc64le/sso/templates/sso74-openj9-postgresql.json
  assets/operator/ocp-ppc64le/sso/templates/sso75-openj9-https.json
  assets/operator/ocp-ppc64le/sso/templates/sso75-openj9-ocp4-x509-https.json
  assets/operator/ocp-ppc64le/sso/templates/sso75-openj9-ocp4-x509-postgresql-persistent.json
  assets/operator/ocp-ppc64le/sso/templates/sso75-openj9-postgresql-persistent.json
  assets/operator/ocp-ppc64le/sso/templates/sso75-openj9-postgresql.json
  assets/operator/ocp-s390x/sso/imagestreams/sso74-openj9-openshift-rhel8.json
  assets/operator/ocp-s390x/sso/imagestreams/sso75-openj9-openshift-rhel8.json
  assets/operator/ocp-s390x/sso/templates/sso74-openj9-https.json
  assets/operator/ocp-s390x/sso/templates/sso74-openj9-ocp4-x509-https.json
  assets/operator/ocp-s390x/sso/templates/sso74-openj9-ocp4-x509-postgresql-persistent.json
  assets/operator/ocp-s390x/sso/templates/sso74-openj9-postgresql-persistent.json
  assets/operator/ocp-s390x/sso/templates/sso74-openj9-postgresql.json
  assets/operator/ocp-s390x/sso/templates/sso75-openj9-https.json
  assets/operator/ocp-s390x/sso/templates/sso75-openj9-ocp4-x509-https.json
  assets/operator/ocp-s390x/sso/templates/sso75-openj9-ocp4-x509-postgresql-persistent.json
  assets/operator/ocp-s390x/sso/templates/sso75-openj9-postgresql-persistent.json
  assets/operator/ocp-s390x/sso/templates/sso75-openj9-postgresql.json
  assets/operator/ocp-x86_64/sso/imagestreams/sso74-openshift-rhel8.json
  assets/operator/ocp-x86_64/sso/imagestreams/sso75-openshift-rhel8.json
  assets/operator/ocp-x86_64/sso/templates/sso74-https.json
  assets/operator/ocp-x86_64/sso/templates/sso74-ocp4-x509-https.json
  assets/operator/ocp-x86_64/sso/templates/sso74-ocp4-x509-postgresql-persistent.json
  assets/operator/ocp-x86_64/sso/templates/sso74-postgresql-persistent.json
  assets/operator/ocp-x86_64/sso/templates/sso74-postgresql.json
  assets/operator/ocp-x86_64/sso/templates/sso75-https.json
  assets/operator/ocp-x86_64/sso/templates/sso75-ocp4-x509-https.json
  assets/operator/ocp-x86_64/sso/templates/sso75-ocp4-x509-postgresql-persistent.json
  assets/operator/ocp-x86_64/sso/templates/sso75-postgresql-persistent.json
  assets/operator/ocp-x86_64/sso/templates/sso75-postgresql.json
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#406 Bug 2027745: Allowing ImageStream creation when config registry empty
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
