Repository openshift/cluster-samples-operator, pull requests merged in 2023-07, with the labels that each got.

#504 OCPBUGS-15754: Update Jenkins and Jenkins Agent Base image versions
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#505 [release-4.13] OCPBUGS-15756: Update Jenkins and Jenkins Agent Base image versions
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json
Labels: approved, lgtm, cherry-pick-approved, qe-approved, px-approved, docs-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#506 [release-4.12] OCPBUGS-15757: Update Jenkins and Jenkins Agent Base image versions
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json
Labels: approved, lgtm, cherry-pick-approved, qe-approved, px-approved, docs-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#507 [release-4.11] OCPBUGS-15758: Update Jenkins and Jenkins Agent Base image versions
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json
Labels: approved, lgtm, cherry-pick-approved, qe-approved, px-approved, docs-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#510 reconcile status when clusteroperator changes
  pkg/operator/controller.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/build.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/console.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/image.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/interface.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/network.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/project.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/config/v1/scheduler.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/factory.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/generic.go
  vendor/github.com/openshift/client-go/config/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/apiserver.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/authentication.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/build.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusteroperator.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/clusterversion.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/console.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/dns.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/expansion_generated.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/featuregate.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/image.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/infrastructure.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/ingress.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/network.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/oauth.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/operatorhub.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/project.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/proxy.go
  vendor/github.com/openshift/client-go/config/listers/config/v1/scheduler.go
  vendor/modules.txt
Labels: approved, lgtm
