Repository openshift/cluster-samples-operator, pull requests merged in 2023-02, with the labels that each got.

#485 OCPBUGS-6811: Update Cluster Sample Operator dependencies and libraries for OCP 4.13
  assets/operator/ocp-aarch64/golang/imagestreams/golang-rhel-aarch64.json
  assets/operator/ocp-ppc64le/golang/imagestreams/golang-rhel.json
  assets/operator/ocp-s390x/golang/imagestreams/golang-rhel.json
  assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-rhel.json
  assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-runtime-rhel.json
  assets/operator/ocp-x86_64/fis/templates/s2i-fuse711-spring-boot-2-camel-rest-3scale.json
  assets/operator/ocp-x86_64/fis/templates/s2i-fuse711-spring-boot-2-camel-xml.json
  assets/operator/ocp-x86_64/fis/templates/s2i-fuse711-spring-boot-2-camel.json
  assets/operator/ocp-x86_64/golang/imagestreams/golang-rhel.json
  assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-centos.json
  assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-runtime-centos.json
  assets/operator/okd-x86_64/golang/imagestreams/golang-centos.json
  assets/operator/okd-x86_64/openliberty/imagestreams/openliberty.json
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#487 OCPBUGS-855: When setting allowedRegistries urls the openshift-samples operator is degraded
  pkg/stub/handler.go
  pkg/stub/handler_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#491 update Jenkins to use v4.12 imagestreams
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-agent-base-centos.json
  assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-centos.json
Labels: approved, lgtm, qe-approved, px-approved, docs-approved
