Repository openshift/cluster-samples-operator, pull requests merged in 2023-03, with the labels that each got.

#494 Fix jira component
  OWNERS
Labels: approved, lgtm, qe-approved, px-approved, docs-approved

#492 [release-4.12] OCPBUGS-10918: update Jenkins to v4.12
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-aarch64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-ppc64le/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-s390x/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-agent-base-rhel.json
  assets/operator/ocp-x86_64/jenkins/imagestreams/jenkins-rhel.json
  assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-agent-base-centos.json
  assets/operator/okd-x86_64/jenkins/imagestreams/jenkins-centos.json
Labels: approved, lgtm, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-important, jira/valid-reference

#495 OCPBUGS-10910: Add network tools imagestreams
  manifests/08-openshift-imagestreams.yaml
  manifests/image-references
Labels: approved, lgtm, bugzilla/valid-bug, qe-approved, px-approved, docs-approved, jira/severity-low, jira/valid-bug, jira/valid-reference
