Repository openshift/cluster-samples-operator, pull requests merged in 2025-04, with the labels that each got.

#618 OCPBUGS-54349: cluster-samples-operator - fix failing unit tests MacBook (ARM chip)
  pkg/stub/handler_test.go
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#621 OCPBUGS-54479: Periodic sync of OKD samples
  assets/operator/okd-x86_64/dotnet/imagestreams/dotnet-runtime.json
  assets/operator/okd-x86_64/dotnet/imagestreams/dotnet.json
  assets/operator/okd-x86_64/nodejs/imagestreams/nodejs-centos.json
  assets/operator/okd-x86_64/openliberty/imagestreams/openliberty.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#622 OCPBUGS-54471: Periodic sync of supported OCP samples
  assets/operator/ocp-aarch64/dotnet/imagestreams/dotnet-rhel-aarch64.json
  assets/operator/ocp-aarch64/dotnet/imagestreams/dotnet-runtime-rhel-aarch64.json
  assets/operator/ocp-aarch64/nodejs/imagestreams/nodejs-rhel-aarch64.json
  assets/operator/ocp-ppc64le/dotnet/imagestreams/dotnet-rhel-ppc64le.json
  assets/operator/ocp-ppc64le/dotnet/imagestreams/dotnet-runtime-rhel-ppc64le.json
  assets/operator/ocp-ppc64le/nodejs/imagestreams/nodejs-rhel.json
  assets/operator/ocp-s390x/dotnet/imagestreams/dotnet-rhel-s390x.json
  assets/operator/ocp-s390x/dotnet/imagestreams/dotnet-runtime-rhel-s390x.json
  assets/operator/ocp-s390x/nodejs/imagestreams/nodejs-rhel.json
  assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-rhel.json
  assets/operator/ocp-x86_64/dotnet/imagestreams/dotnet-runtime-rhel.json
  assets/operator/ocp-x86_64/nodejs/imagestreams/nodejs-rhel.json
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#625 OCPBUGS-54591: only update LastTransitionTime if operator status change
  pkg/operatorstatus/operatorstatus.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#626 OCPBUGS-54589: Adding filter to clusterOperatorInformerEventHandler
  pkg/operator/controller.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#628 [release-4.13] OCPBUGS-54812: add rhdmalone to owners
  OWNERS
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference
