Repository openshift/cluster-samples-operator, pull requests merged in 2025-03, with the labels that each got.

#601 OCPBUGS-45049: Adding mutex to func createSamples on handler.go
  pkg/stub/handler.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#602 OCPBUGS-52346: bump x/oauth2 to version 0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#603 OCPBUGS-52379: relevant references to master renamed in README.md
  README.md
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/valid-reference

#607 OCPBUGS-52848: Revert "OCPBUGS-45049: Adding mutex to func createSamples on handler.go"
  pkg/stub/handler.go
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#606 OCPBUGS-52848: Revert "OCPBUGS-52346: bump x/oauth2 to version 0.27.0"
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: approved, lgtm, qe-approved, px-approved, docs-approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#608 OCPBUGS-52848: Unrevert the revert "OCPBUGS-52346: bump x/oauth2 to version 0.27.0"
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#609 OCPBUGS-52848: Unrevert the revert "OCPBUGS-45049: Adding mutex to func createSamples on handler.go"
  pkg/stub/handler.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-important, jira/valid-reference

#613 OCPBUGS-54149: Updates to README.md
  README.md
Labels: approved, lgtm, jira/severity-low, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#616 OCPBUGS-54347: add rhdmalone to owners
  OWNERS
Labels: approved, lgtm, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference, acknowledge-critical-fixes-only
